[package]
name = "test-no-std"
version = "0.7.1"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
libc = { version = "0.2.119", default-features = false }

# local dependencies
ac-compose-macros = { version = "0.5", default-features = false, path = "../compose-macros", optional = true, features = ["disable_target_static_assertions", "sync-api"] }
ac-node-api = { version = "0.6", default-features = false, path = "../node-api", optional = true, features = ["disable_target_static_assertions"] }
ac-primitives = { version = "0.9", default-features = false, path = "../primitives", optional = true, features = ["disable_target_static_assertions"] }
substrate-api-client = { version = "0.17", default-features = false, optional = true, features = ["disable_target_static_assertions", "sync-api"] }

# substrate dependencies
sp-io = { default-features = false, features = ["disable_oom", "disable_panic_handler"], version = "32.0" }

[features]
# It is better to test the no-std crates standalone (don't enable both features at the same time) because dependency
# leaks might cause successful `no-std` builds, which would fail in standalone build.
api-client = ["substrate-api-client"]
compose-macros = ["ac-compose-macros"]
node-api = ["ac-node-api"]
primitives = ["ac-primitives"]
