[package]
name = "ac-examples-async"
version = "0.18.0"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", features = ['derive'] }
env_logger = "0.11"
log = "0.4.14"
serde_json = "1.0.79"
tokio = { version = "1.24", features = ["rt-multi-thread", "macros", "time"] }
tokio-util = "0.7.8"
wabt = "0.10.0"

# Substrate dependencies
frame-support = { version = "36.0.0" }
frame-system = { version = "36.1.0" }
#kitchensink-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-crates-io-v1.14.0" }
pallet-balances = { version = "37.0.0" }
pallet-identity = { version = "36.0.0" }
pallet-staking = { version = "36.0.0" }
sp-core = { version = "34.0.0" }
sp-keyring = { version = "38.0.0" }
sp-runtime = { version = "38.0.0" }
sp-weights = { version = "31.0.0" }

# local deps
substrate-api-client = { path = "../..", version = "0.18", features = ["staking-xt", "contracts-xt", "disable-metadata-hash-check"] }
