[package]
name = "ac-examples-wasm"
version = "0.18.0"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
sp-core = { version = "34.0.0", default-features = false, features = ["full_crypto", "serde"] }
sp-runtime = { version = "38.0.0", default-features = false }
pallet-balances = { version = "37.0.0", default-features = false }

substrate-api-client = { path = "../..", version = "0.18", default-features = false }
